// <auto-generated />
using System;
using BolsoEmDia.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BolsoEmDia.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909122941_EntidadesFinanceiras")]
    partial class EntidadesFinanceiras
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.AporteMeta", b =>
                {
                    b.Property<int>("IdAporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_aporte");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAporte"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<int>("IdMeta")
                        .HasColumnType("integer")
                        .HasColumnName("id_meta");

                    b.Property<int?>("IdTransacao")
                        .HasColumnType("integer")
                        .HasColumnName("id_transacao");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdAporte")
                        .HasName("pk_aportes_meta");

                    b.HasIndex("IdMeta")
                        .HasDatabaseName("ix_aportes_meta_id_meta");

                    b.HasIndex("IdTransacao")
                        .HasDatabaseName("ix_aportes_meta_id_transacao");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_aportes_meta_id_usuario");

                    b.ToTable("aportes_meta", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Cartao", b =>
                {
                    b.Property<int>("IdCartao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cartao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCartao"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<int>("DiaFechamento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_fechamento");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("integer")
                        .HasColumnName("dia_vencimento");

                    b.Property<int>("IdContaPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta_pagamento");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<decimal>("LimiteTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_total");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("IdCartao")
                        .HasName("pk_cartoes");

                    b.HasIndex("IdContaPagamento")
                        .HasDatabaseName("ix_cartoes_id_conta_pagamento");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_cartoes_id_usuario");

                    b.ToTable("cartoes", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<int?>("IdCategoriaPai")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_pai");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("IdCategoria")
                        .HasName("pk_categorias");

                    b.HasIndex("IdCategoriaPai")
                        .HasDatabaseName("ix_categorias_id_categoria_pai");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_categorias_id_usuario");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_compra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdCartao")
                        .HasColumnType("integer")
                        .HasColumnName("id_cartao");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdRecorrencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_recorrencia");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("IdCompra")
                        .HasName("pk_compras");

                    b.HasIndex("IdCartao")
                        .HasDatabaseName("ix_compras_id_cartao");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("ix_compras_id_categoria");

                    b.HasIndex("IdRecorrencia")
                        .HasDatabaseName("ix_compras_id_recorrencia");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_compras_id_usuario");

                    b.ToTable("compras", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Conta", b =>
                {
                    b.Property<int>("IdConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_conta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConta"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo_inicial");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("IdConta")
                        .HasName("pk_contas");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_contas_id_usuario");

                    b.ToTable("contas", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Fatura", b =>
                {
                    b.Property<int>("IdFatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fatura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFatura"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fechamento");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<int>("IdCartao")
                        .HasColumnType("integer")
                        .HasColumnName("id_cartao");

                    b.Property<int?>("IdTransacaoPagamento")
                        .HasColumnType("integer")
                        .HasColumnName("id_transacao_pagamento");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<DateOnly>("MesReferencia")
                        .HasColumnType("date")
                        .HasColumnName("mes_referencia");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("IdFatura")
                        .HasName("pk_faturas");

                    b.HasIndex("IdTransacaoPagamento")
                        .HasDatabaseName("ix_faturas_id_transacao_pagamento");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_faturas_id_usuario");

                    b.HasIndex("IdCartao", "MesReferencia")
                        .IsUnique()
                        .HasDatabaseName("ix_faturas_id_cartao_mes_referencia");

                    b.ToTable("faturas", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.MetaEconomia", b =>
                {
                    b.Property<int>("IdMeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_meta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMeta"));

                    b.Property<bool>("Concluida")
                        .HasColumnType("boolean")
                        .HasColumnName("concluida");

                    b.Property<DateTime?>("DataAlvo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alvo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<int?>("IdConta")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<decimal>("ValorAlvo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_alvo");

                    b.HasKey("IdMeta")
                        .HasName("pk_metas_economia");

                    b.HasIndex("IdConta")
                        .HasDatabaseName("ix_metas_economia_id_conta");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_metas_economia_id_usuario");

                    b.ToTable("metas_economia", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Orcamento", b =>
                {
                    b.Property<int>("IdOrcamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_orcamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOrcamento"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<DateOnly>("MesReferencia")
                        .HasColumnType("date")
                        .HasColumnName("mes_referencia");

                    b.Property<decimal>("ValorMeta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_meta");

                    b.HasKey("IdOrcamento")
                        .HasName("pk_orcamentos");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_orcamentos_id_usuario");

                    b.HasIndex("IdCategoria", "MesReferencia")
                        .IsUnique()
                        .HasDatabaseName("ix_orcamentos_id_categoria_mes_referencia");

                    b.ToTable("orcamentos", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Parcela", b =>
                {
                    b.Property<int>("IdParcela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_parcela");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdParcela"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<int>("IdCompra")
                        .HasColumnType("integer")
                        .HasColumnName("id_compra");

                    b.Property<int>("IdFatura")
                        .HasColumnType("integer")
                        .HasColumnName("id_fatura");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdParcela")
                        .HasName("pk_parcelas");

                    b.HasIndex("IdCompra")
                        .HasDatabaseName("ix_parcelas_id_compra");

                    b.HasIndex("IdFatura")
                        .HasDatabaseName("ix_parcelas_id_fatura");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_parcelas_id_usuario");

                    b.ToTable("parcelas", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Recorrencia", b =>
                {
                    b.Property<int>("IdRecorrencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_recorrencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecorrencia"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inicio");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<int>("DiaGeracao")
                        .HasColumnType("integer")
                        .HasColumnName("dia_geracao");

                    b.Property<int>("Frequencia")
                        .HasColumnType("integer")
                        .HasColumnName("frequencia");

                    b.Property<int?>("IdCartao")
                        .HasColumnType("integer")
                        .HasColumnName("id_cartao");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int?>("IdConta")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<int?>("TipoTransacao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_transacao");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdRecorrencia")
                        .HasName("pk_recorrencias");

                    b.HasIndex("IdCartao")
                        .HasDatabaseName("ix_recorrencias_id_cartao");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("ix_recorrencias_id_categoria");

                    b.HasIndex("IdConta")
                        .HasDatabaseName("ix_recorrencias_id_conta");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_recorrencias_id_usuario");

                    b.ToTable("recorrencias", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Transacao", b =>
                {
                    b.Property<int>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_transacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransacao"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IdConta")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta");

                    b.Property<int?>("IdRecorrencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_recorrencia");

                    b.Property<int?>("IdTransferencia")
                        .HasColumnType("integer")
                        .HasColumnName("id_transferencia");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdTransacao")
                        .HasName("pk_transacoes");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("ix_transacoes_id_categoria");

                    b.HasIndex("IdConta")
                        .HasDatabaseName("ix_transacoes_id_conta");

                    b.HasIndex("IdRecorrencia")
                        .HasDatabaseName("ix_transacoes_id_recorrencia");

                    b.HasIndex("IdTransferencia")
                        .HasDatabaseName("ix_transacoes_id_transferencia");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_transacoes_id_usuario");

                    b.ToTable("transacoes", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Transferencia", b =>
                {
                    b.Property<int>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_transferencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransferencia"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_modificacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<int>("IdContaDestino")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta_destino");

                    b.Property<int>("IdContaOrigem")
                        .HasColumnType("integer")
                        .HasColumnName("id_conta_origem");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IdUsuarioCriacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_criacao");

                    b.Property<string>("IdUsuarioModificacao")
                        .HasColumnType("text")
                        .HasColumnName("id_usuario_modificacao");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdTransferencia")
                        .HasName("pk_transferencias");

                    b.HasIndex("IdContaDestino")
                        .HasDatabaseName("ix_transferencias_id_conta_destino");

                    b.HasIndex("IdContaOrigem")
                        .HasDatabaseName("ix_transferencias_id_conta_origem");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("ix_transferencias_id_usuario");

                    b.ToTable("transferencias", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.AporteMeta", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.MetaEconomia", null)
                        .WithMany("Aportes")
                        .HasForeignKey("IdMeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aportes_meta_metas_economia_id_meta");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Transacao", null)
                        .WithMany()
                        .HasForeignKey("IdTransacao")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_aportes_meta_transacoes_id_transacao");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aportes_meta_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Cartao", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Conta", null)
                        .WithMany()
                        .HasForeignKey("IdContaPagamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cartoes_contas_id_conta_pagamento");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartoes_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Categoria", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoriaPai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_categorias_id_categoria_pai");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Compra", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Cartao", null)
                        .WithMany()
                        .HasForeignKey("IdCartao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_cartoes_id_cartao");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_compras_categorias_id_categoria");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Recorrencia", null)
                        .WithMany()
                        .HasForeignKey("IdRecorrencia")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_compras_recorrencias_id_recorrencia");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compras_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Conta", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contas_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Fatura", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Cartao", null)
                        .WithMany("Faturas")
                        .HasForeignKey("IdCartao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_faturas_cartoes_id_cartao");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Transacao", null)
                        .WithMany()
                        .HasForeignKey("IdTransacaoPagamento")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_faturas_transacoes_id_transacao_pagamento");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_faturas_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.MetaEconomia", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Conta", null)
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_metas_economia_contas_id_conta");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metas_economia_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Orcamento", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamentos_categorias_id_categoria");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamentos_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Parcela", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Compra", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcelas_compras_id_compra");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Fatura", null)
                        .WithMany()
                        .HasForeignKey("IdFatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcelas_faturas_id_fatura");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcelas_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Recorrencia", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Cartao", null)
                        .WithMany()
                        .HasForeignKey("IdCartao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recorrencias_cartoes_id_cartao");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recorrencias_categorias_id_categoria");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Conta", null)
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recorrencias_contas_id_conta");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recorrencias_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Transacao", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transacoes_categorias_id_categoria");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Conta", null)
                        .WithMany()
                        .HasForeignKey("IdConta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transacoes_contas_id_conta");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Recorrencia", null)
                        .WithMany()
                        .HasForeignKey("IdRecorrencia")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transacoes_recorrencias_id_recorrencia");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Transferencia", null)
                        .WithMany("Pernas")
                        .HasForeignKey("IdTransferencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transacoes_transferencias_id_transferencia");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transacoes_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Transferencia", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.Conta", null)
                        .WithMany()
                        .HasForeignKey("IdContaDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transferencias_contas_id_conta_destino");

                    b.HasOne("BolsoEmDia.Domain.Entidades.Conta", null)
                        .WithMany()
                        .HasForeignKey("IdContaOrigem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transferencias_contas_id_conta_origem");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transferencias_asp_net_users_id_usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BolsoEmDia.Domain.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Cartao", b =>
                {
                    b.Navigation("Faturas");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Compra", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.MetaEconomia", b =>
                {
                    b.Navigation("Aportes");
                });

            modelBuilder.Entity("BolsoEmDia.Domain.Entidades.Transferencia", b =>
                {
                    b.Navigation("Pernas");
                });
#pragma warning restore 612, 618
        }
    }
}
